#!/bin/bash

###############################################################
# SCAN-BUILD SCRIPT
# http://manpages.ubuntu.com/manpages/precise/man1/scan-build.1.html
# https://askubuntu.com/questions/1033808/how-can-clang-static-analyzer-scan-build-be-installed-on-ubuntu-18-04
################################################################

# get argument
INPUT=$1
 
# check if dev mode
if [ "$INPUT" != "dev" ]; then

    # run scan-build on files in src and subdirectories on extension .cpp 
    # > /dev/null to remove standard output
    scan-build --status-bugs g++ -c ${@:2} > /dev/null

    # localize variable of return value to check if bugs are found
    BUGS_FOUND=$?

    # remove binaries used for this script
    rm *.o

    # check if there was any bugs
    if [ $BUGS_FOUND -eq 1 ]
        then
            echo "scan-build: bugs found. build will fail." && exit 1 
        else 
            echo "scan-build: no bugs found." && exit 0
    fi
fi


